// Code generated by MCHP Chatbot
/**
  Generated Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This is the main file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs

  Description:
    This header file provides implementations for driver APIs for all modules
  selected in the GUI. Generation Information : Product Revision  :  PIC10 /
  PIC12 / PIC16 MCUs - 1.81.8 Device            :  PIC16F1936 Driver Version
  :  2.00
 */

/*
    (c) 2018 Microchip Technology Inc. and its subsidiaries.
    ... License statement omitted for brevity ...
 */

// 20251118 V01 CS:
// 按鍵OK
// LCD OK
// Timer1 10ms為基礎時間單為
// 設定為1倍   10ms    0.01S
// 設定為10倍  100ms   0.1S
// 設定為100倍 1000ms  1S
// 計數0~999

// 20251119 V02 CS:
// 處理LCD太多層 STACK爆掉
// 開機讀取EEPROM資料 SetTimer1,SetTimer2
// 將SetTimer1轉換成4個數字顯示
// 將SetTimer2轉換成4個數字顯示
// 1.開機時先顯示之前設定的時間
// 2.短按啟動/結束鍵(K4)，可以啟動或結束計時
// 3.長按設定鍵(K2)，進入時間選擇模式
// 4.設定時先選擇時間的模式:1S/0.1S/0.01S
// 5.按選擇鍵(K1)由1S->0.1S->0.01S->回到1S，短按設定鍵(K2)，進入時間設定模式
// 6.按選擇鍵(K3)由1S<-0.1S<-0.01S<-回到1S，短按設定鍵(K2)，進入時間設定模式
// 7.T1時間設定模式依序由左邊第一個數字開始設定，按K1或K3設定(0~9)，短按設定鍵(K2)進入設定第2個數字
// 8.依序設定完數字2/數字3/數字4
// 如果設定完成長按設定鍵(K2)進入T2時間設定，短按(K2)則再回到T1的數字1做設定
// 9.同T1時間設定方式，設定T2時間 如果設定完成長按設定鍵(K2)進入T2時間設定

// 20251120 V03 CS:
// 加入EEPROM功能
// 加入RELAY功能
// 4個按鍵短按功能OK
// 4個按鍵長按功能OK
// 輸出鍵(K4)計時切換Relay ON/OFF
// 上鍵(K1)
// 設定鍵(K2)
// 下鍵(K3)
// 輸出鍵(K4)
// LCD每秒更新畫面
// normal和functionSet mdoe畫面切換

// 11251121 V04 CS:94EE
// 切換Relay ON/OFF，改放在TMR1_10msEven執行，避免被LCD卡到造成時間不準。
// DispFunctionSet功能完成
// 增加第1行後方顯示ON/OFF(OUT ON/OFF)
// TimeAdjustment完成
// 功能完成

// 20251121 V05 CS:
// 修正游標位置(TimeAdjustment)
// 加快LCD更新速度 250ms
// 加快按鍵速度 短按 10ms
// 加快按鍵速度 長按 400ms

// 20251124 V06 CS:6A95
// 設定完成將資料存入EEPROM
// 修正顯示問題
// 改成有資料更新才更新LCD，避免LCD閃爍
// 增加K1&K3長按功能

// 20260105 V07 CS:F9F3
// 1.單位:秒(固定)
// 2.簡化設定操作
// 3.執行時顯示秒數
// 4.修正腳位設定

#include "Key.h"
#include "RelayControl.h"
// #include "TimerEven.h"
#include "eeprom.h"
// #include "hd44780_i2c.h"
#include "LCD.h"
#include "mcc_generated_files/mcc.h"
#include "mcc_generated_files/pin_manager.h"
#include <builtins.h>
#include <pic.h>

int main(void) {
  // initialize the device
  SYSTEM_Initialize();
  // Modify the definition name of the interrupt handler
  TMR0_SetInterruptHandler(TMR0_10msEven);
  TMR1_SetInterruptHandler(TMR1_10msEven);

  // Enable the Global Interrupts
  INTERRUPT_GlobalInterruptEnable();
  // Enable the Peripheral Interrupts
  INTERRUPT_PeripheralInterruptEnable();

  RelayControl_Init();
  POWER_ON_EEPROM_READ();
  KEY_Init();
  LCD_Init();

  // 開機顯示
  PWR_ON_DISP();

  while (1) {
    // 10ms 進入一次    // 更新按鍵狀態
    CheckKey();

    // 每秒更新LCD晝面
    DISP_SHOW();

    switch (LCD_DispMode) {
    case eNormal:
      Normal();
      break;
    case eTimeSetting1: // 修改所選計時器時間
      TimeSetting1();
      break;
    case eTimeSetting2: // 修改所選計時器時間
      TimeSetting2();
      break;
    case eTimerCount:
      TimerCount();
    default:
      break;
    }
  }

  return 0;
}

/**
 End of File
 */
