// Code generated by MCHP Chatbot
#ifndef KEY_H
#define KEY_H

#include "mcc_generated_files/mcc.h"
#include <stdint.h>
#include <stdbool.h>

#define KEY_NUM 4

typedef enum {
    KEY_IDLE = 0,
    KEY_DEBOUNCE,
    KEY_PRESS
} KEY_STATE_t;

typedef struct {
    KEY_STATE_t state;
    uint16_t debounce_cnt;
    uint16_t press_cnt;
    bool short_press_flag;   // 單次短按
    bool long_press_flag;    // 單次長按
    bool reported;           // 防止同一輪連續回報
} KeyInfo_t;

// 每個按鍵一組狀態
extern KeyInfo_t g_keys[KEY_NUM];

// 需於主程式10ms週期呼叫
void Key_ScanTask(void);

// 初始化（電源上電時呼叫一次）
void Key_Init(void);

// 狀態查詢API，每顆按鍵回傳true後使用者必須立即清掉對應flag
bool Key_ShortPressed(uint8_t idx); // idx: 0~3 對應Button1~4
bool Key_LongPressed(uint8_t idx);

#endif /* KEY_H */
