// Code generated by MCHP Chatbot
/**
  Generated Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This is the main file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs

  Description:
    This header file provides implementations for driver APIs for all modules
  selected in the GUI. Generation Information : Product Revision  :  PIC10 /
  PIC12 / PIC16 MCUs - 1.81.8 Device            :  PIC16F1936 Driver Version
  :  2.00
*/

/*
    (c) 2018 Microchip Technology Inc. and its subsidiaries.
    ... License statement omitted for brevity ...
*/

#include "Key.h"
#include "TimerEven.h"
#include "hd44780_i2c.h"
#include "mcc_generated_files/mcc.h"
#include <stdio.h>

extern void TMR0_Even_10msEV(void);
extern void TMR1_EvenHandler(void);

char buf[17]; // 用於LCD顯示暫存

int main(void) {
  // initialize the device
  SYSTEM_Initialize();
  TMR0_SetInterruptHandler(TMR0_Even_10msEV);
  TMR1_SetInterruptHandler(TMR1_EvenHandler);
  LCD_Init();
  LCD_SetCursor(0, 0); // 第一行第一格
  Key_Init(); // ===== 加入此行初始化按鍵模組 =====

  short_led_SetHigh();
  long_led_SetHigh();
  
  while (1) {
    // Add your application code
    for(int i = 0; i < KEY_NUM; i++) {
      if (Key_ShortPressed(i)) {
        LCD_SetCursor(0, 1);     // 設定第二行
        sprintf(buf, "BTN %d Short", i+1);
        LCD_Print(buf);
      }
      if (Key_LongPressed(i)) {
        LCD_SetCursor(0, 1);
        sprintf(buf, "BTN %d Long", i+1);
        LCD_Print(buf);
      }
    }
  }
  return 0;
}

/**
 End of File
*/

