// Code generated by MCHP Chatbot

#include "TimerEven.h"
#include <stdbool.h>
#include "Key.h"

uint16_t T1_1ms_cnt=0;
bool    fT1_1ms_flag=false;

void TMR0_Even_10msEV(void){
    Key_ScanTask();   // ==== 每10ms呼叫一次按鍵掃描功能 ====
}

void TMR1_EvenHandler(void){
    T1_1ms_cnt++;
}