// Code generated by MCHP Chatbot
/**
  Generated Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This is the main file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs

  Description:
    This header file provides implementations for driver APIs for all modules
  selected in the GUI. Generation Information : Product Revision  :  PIC10 /
  PIC12 / PIC16 MCUs - 1.81.8 Device            :  PIC16F1936 Driver Version
  :  2.00
 */

/*
    (c) 2018 Microchip Technology Inc. and its subsidiaries.
    ... License statement omitted for brevity ...
 */

// 20251118 V01 CS:
// 按鍵OK
// LCD OK
// Timer1 10ms為基礎時間單為
// 設定為1倍   10ms    0.01S
// 設定為10倍  100ms   0.1S
// 設定為100倍 1000ms  1S
// 計數0~999

// 20251119 V02 CS:
// 處理LCD太多層 STACK爆掉
// 開機讀取EEPROM資料 SetTimer1,SetTimer2
// 將SetTimer1轉換成4個數字顯示
// 將SetTimer2轉換成4個數字顯示
// 1.開機時先顯示之前設定的時間
// 2.短按啟動/結束鍵(K4)，可以啟動或結束計時
// 3.長按設定鍵(K2)，進入時間選擇模式
// 4.設定時先選擇時間的模式:1S/0.1S/0.01S
// 5.按選擇鍵(K1)由1S->0.1S->0.01S->回到1S，短按設定鍵(K2)，進入時間設定模式
// 6.按選擇鍵(K3)由1S<-0.1S<-0.01S<-回到1S，短按設定鍵(K2)，進入時間設定模式
// 7.T1時間設定模式依序由左邊第一個數字開始設定，按K1或K3設定(0~9)，短按設定鍵(K2)進入設定第2個數字
// 8.依序設定完數字2/數字3/數字4
// 如果設定完成長按設定鍵(K2)進入T2時間設定，短按(K2)則再回到T1的數字1做設定
// 9.同T1時間設定方式，設定T2時間 如果設定完成長按設定鍵(K2)進入T2時間設定

// 20251120 V03 CS:
// 加入EEPROM功能
// 加入RELAY功能
// 4個按鍵短按功能OK
// 4個按鍵長按功能OK
// 輸出鍵(K4)計時切換Relay ON/OFF
// 上鍵(K1)
// 設定鍵(K2)
// 下鍵(K3)
// 輸出鍵(K4)
// LCD每秒更新畫面
// normal和functionSet mdoe畫面切換

// 11251121 V04 CS:94EE
// 切換Relay ON/OFF，改放在TMR1_10msEven執行，避免被LCD卡到造成時間不準。
// DispFunctionSet功能完成
// 增加第1行後方顯示ON/OFF(OUT ON/OFF)
// TimeAdjustment完成
// 功能完成

// 20251121 V05 CS:
// 修正游標位置(TimeAdjustment)
// 加快LCD更新速度 250ms
// 加快按鍵速度 短按 10ms
// 加快按鍵速度 長按 400ms

// 20251124 V06 CS:B982
// 設定完成將資料存入EEPROM
// 修正顯示問題

#include "Key.h"
#include "RelayControl.h"
#include "TimerEven.h"
#include "eeprom.h"
#include "hd44780_i2c.h"
#include "mcc_generated_files/mcc.h"
#include "mcc_generated_files/pin_manager.h"
#include <pic.h>

int main(void) {
  // initialize the device
  SYSTEM_Initialize();
  TMR0_SetInterruptHandler(TMR0_10msEven);
  TMR1_SetInterruptHandler(TMR1_10msEven);

  // Enable the Global Interrupts
  INTERRUPT_GlobalInterruptEnable();

  // Enable the Peripheral Interrupts
  INTERRUPT_PeripheralInterruptEnable();

  RelayControl_Init();
  POWER_ON_EEPROM_READ();
  KEY_Init(); // ===== 加入此行初始化按鍵模組 =====
  LCD_Init();

  // 開機LCD顯示
  // LCD_SetCursor(0, 0); // 第一行第一格
  // DispNormal(TimeMode, _T1_, SetTimer1_cnt, buf);
  // LCD_Print(buf);

  // LCD_SetCursor(0, 1); // 第二行第一格
  // DispNormal(TimeMode, _T2_, SetTimer2_cnt, buf);
  // LCD_Print(buf);

  while (1) {
    // 10ms 進入一次    // 更新按鍵狀態
    if (fT0_fT10ms) {
      fT0_fT10ms = 0;
      // short_led_Toggle();
      key[0].fKeyIn = (button1_GetValue() == LOW);
      key[1].fKeyIn = (button2_GetValue() == LOW);
      key[2].fKeyIn = (button3_GetValue() == LOW);
      key[3].fKeyIn = (button4_GetValue() == LOW);
      KEY_ScanAll();
    }

    // 每秒更新LCD晝面
    if (fT0_1second || fLCD_updata) {
      fT0_1second = 0;
      fLCD_updata = 0;
      if (OutState)
        fDOT = !fDOT;
      else
        fDOT = 0;
      // LCD_Command(CLEAR_DISPLAY);
      switch (LCD_DispMode) {
      case eNormal:
        LCD_SetCursor(0, 0); // 第1行
        DispNormal(TimeMode, _T1_, SetTimer1_cnt, buf);
        LCD_Print(buf);

        LCD_SetCursor(0, 1); // 第2行第
        DispNormal(TimeMode, _T2_, SetTimer2_cnt, buf);
        LCD_Print(buf);
        break;

      case eFunctionSet:
        LCD_SetCursor(0, 0); // 第1行
        sprintf(buf, "FunctionSet Mode");
        LCD_Print(buf);
        LCD_SetCursor(0, 1); // 第2行
        DispFunctionSet(TimeMode, _T2_, SetTimer2_cnt, buf);
        LCD_Print(buf);
        break;

      case eTimeAdjustment:
        LCD_SetCursor(0, 0); // 第1行
        DispTimeAdjustment(TimeMode, _T1_, SetTimer1_cnt, buf);
        LCD_Print(buf);
        LCD_SetCursor(0, 1); // 第2行
        DispTimeAdjustment(TimeMode, _T2_, SetTimer2_cnt, buf);
        LCD_Print(buf);

        LCD_SetCursor(Cursor_pos, 0); // 第1行
        LCD_Command(DISP_ON_CUR_ON);  // Display ON, Cursor OFF
        break;

      default:
        break;
      }
    }

    switch (LCD_DispMode) {
    case eNormal:
      Normal();
      break;
    case eFunctionSet:
      FunctionSet();
      break;
    case eTimeAdjustment:
      TimeAdjustment();
      break;
    default:
      break;
    }
  }
  return 0;
}

/**
 End of File
 */
